### ISSUE TITLE
Ability to search Title fields as well as note fields

### ISSUE THREAD

**Issue by navigator8** [notegraph/notegraph-mobile#13]
Ability to search Title fields as well as note fields in the connection fields and home search screen (page)

**Comment by romanlv** [comment]
@navigator8 search in the title works for me, can you double check? or provide steps to reproduce

**Comment by navigator8** [comment]
Here is a video on how to reproduce the steps.

in the video i am looking for a note titled Node 1. I cannot find it until I add Node 1 in the text.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
